<?xml version="1.0" encoding="utf-8"?><Database Name="Tracking" Class="EmployeeDataClassDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-5KJPFCB\SQLEXPRESS;Initial Catalog=Tracking;Integrated Security=True" SettingsObjectName="DAL.Properties.Settings" SettingsPropertyName="TrackingConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.DEPARTAMENTS" Member="DEPARTAMENTS">
    <Type Name="DEPARTAMENTS">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DEPARTAMENT_NAME" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="DEPARTAMENTS_USERS" Member="USERS" ThisKey="ID" OtherKey="DEPARTAMENT_ID" Type="USERS" />
      <Association Name="DEPARTAMENTS_POSITIONS" Member="POSITIONS" ThisKey="ID" OtherKey="DEPARTAMENT_ID" Type="POSITIONS" />
    </Type>
  </Table>
  <Table Name="dbo.USERS" Member="USERS">
    <Type Name="USERS">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="USER_NO" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NAME" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SURNAME" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IMAGE_PATH" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DEPARTAMENT_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SALARY" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="ADRESS" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="BIRTH_DAY" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="PASSWORD" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="IS_ADMIN" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="USERS_PERMISSIONS" Member="PERMISSIONS" ThisKey="ID" OtherKey="EMPLOYEE_ID" Type="PERMISSIONS" />
      <Association Name="USERS_SALARIES" Member="SALARIES" ThisKey="ID" OtherKey="EMPLOYEE_ID" Type="SALARIES" />
      <Association Name="USERS_TASKS" Member="TASKS" ThisKey="ID" OtherKey="EMPLOYEE_ID" Type="TASKS" />
      <Association Name="DEPARTAMENTS_USERS" Member="DEPARTAMENTS" ThisKey="DEPARTAMENT_ID" OtherKey="ID" Type="DEPARTAMENTS" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MONTHS" Member="MONTHS">
    <Type Name="MONTHS">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MONTH_NAME" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="MONTHS_SALARIES" Member="SALARIES" ThisKey="ID" OtherKey="MONTH_ID" Type="SALARIES" />
    </Type>
  </Table>
  <Table Name="dbo.PERMISSIONS" Member="PERMISSIONS">
    <Type Name="PERMISSIONS">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EMPLOYEE_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PERMISSION_START_DATE" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="PERMISSION_END_DATE" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="PERMISSION_STATE" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PERMISSION_EXPLANATION" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PERMISSION_DAY" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="USERS_PERMISSIONS" Member="USERS" ThisKey="EMPLOYEE_ID" OtherKey="ID" Type="USERS" IsForeignKey="true" />
      <Association Name="STATETS_PERMISSIONS_PERMISSIONS" Member="STATETS_PERMISSIONS" ThisKey="PERMISSION_STATE" OtherKey="ID" Type="STATETS_PERMISSIONS" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.POSITIONS" Member="POSITIONS">
    <Type Name="POSITIONS">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="POSITION_NAME" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DEPARTAMENT_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="DEPARTAMENTS_POSITIONS" Member="DEPARTAMENTS" ThisKey="DEPARTAMENT_ID" OtherKey="ID" Type="DEPARTAMENTS" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SALARIES" Member="SALARIES">
    <Type Name="SALARIES">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EMPLOYEE_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AMOUNT" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="YEAR" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MONTH_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="MONTHS_SALARIES" Member="MONTHS" ThisKey="MONTH_ID" OtherKey="ID" Type="MONTHS" IsForeignKey="true" />
      <Association Name="USERS_SALARIES" Member="USERS" ThisKey="EMPLOYEE_ID" OtherKey="ID" Type="USERS" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.STATES" Member="STATES">
    <Type Name="STATES">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="STATE_NAME" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="STATES_TASKS" Member="TASKS" ThisKey="ID" OtherKey="TASK_STATE" Type="TASKS" />
    </Type>
  </Table>
  <Table Name="dbo.STATETS_PERMISSIONS" Member="STATETS_PERMISSIONS">
    <Type Name="STATETS_PERMISSIONS">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="STATE_NAME" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="STATETS_PERMISSIONS_PERMISSIONS" Member="PERMISSIONS" ThisKey="ID" OtherKey="PERMISSION_STATE" Type="PERMISSIONS" />
    </Type>
  </Table>
  <Table Name="dbo.TASKS" Member="TASKS">
    <Type Name="TASKS">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EMPLOYEE_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TASK_TITLE" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="TASK_CONTENT" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TASK_START" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TASK_DELIVERY_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TASK_STATE" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="STATES_TASKS" Member="STATES" ThisKey="TASK_STATE" OtherKey="ID" Type="STATES" IsForeignKey="true" />
      <Association Name="USERS_TASKS" Member="USERS" ThisKey="EMPLOYEE_ID" OtherKey="ID" Type="USERS" IsForeignKey="true" />
    </Type>
  </Table>
</Database>